### register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "marketscenter.pg@gmail.com",
    "firstName": "Markets",
    "lastName": "Center",
    "password": "a1s2d3f4"
}

### login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "clau.neme@gmail.com",
    "password": "a1s2d3f4"
}

### whoami
GET http://localhost:4000/api/user/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1ZDJmNzQ2LTE1NmEtNDQwYi1iZGJjLTViNmViMGE5ZjdlMiIsImlhdCI6MTY1NDI4ODEyMCwiZXhwIjoxNjU0Mjg5OTIwfQ.rPTQNQtWuM1lHZOAUwfDdJwsZa6LV2aaGAnVfwpCGTU

### forgotPass
POST http://localhost:4000/api/auth/forgotPass
Content-Type: application/json

{
    "email": "foca@gmail.com"
}

### resetPAss
PUT http://localhost:4000/api/auth/resetPass/20effc5ebef7c395d70910530d7a5dcc512dc02a
Content-Type: application/json

{
    "password": "123456"
}
