### register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "marketscenter.pg@gmail.com",
    "firstName": "Markets",
    "lastName": "Center",
    "password": "a1s2d3f4"
}

### login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "marketscenter.pg@gmail.com",
    "password": "a1s2d3f4"
}

### whoami
GET http://localhost:4000/api/user/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6Ijg0NDFmNzUxLTQ3YWQtNGNkMS1iOTgwLTk4MzUzYmQ5ZTA3MSIsInJvbGUiOiIyNzgxIn0sImlhdCI6MTY1NTEyNTI0MSwiZXhwIjoxNjU1MTI3MDQxfQ.0YHq7EubR7v3VYGU4dlFCwz9vgzt3bwbzELXRTdAE3c

### forgotPass
POST http://localhost:4000/api/auth/forgotPass
Content-Type: application/json

{
    "email": "foca@gmail.com"
}

### resetPAss
PUT http://localhost:4000/api/auth/resetPass/20effc5ebef7c395d70910530d7a5dcc512dc02a
Content-Type: application/json

{
    "password": "123456"
}


### logout
GET http://localhost:4000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6Ijg0NDFmNzUxLTQ3YWQtNGNkMS1iOTgwLTk4MzUzYmQ5ZTA3MSIsInJvbGUiOiIyNzgxIn0sImlhdCI6MTY1NTEyNjgyNywiZXhwIjoxNjU1MTI4NjI3fQ.iPa4rH-t0tEUxGoiZ8HgpuR9zBuokQGQxTORfFwjnRs