### add Operation
POST http://localhost:4000/api/op/addOp/c76fe122-7478-46cc-9100-467322c3bf77
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM3NmZlMTIyLTc0NzgtNDZjYy05MTAwLTQ2NzMyMmMzYmY3NyIsImlhdCI6MTY1NDI4ODMwMywiZXhwIjoxNjU0MjkwMTAzfQ.dPGw-NbO94eM5EuWKD-QotY4VMo3zhqRBcD9N1XQ1uU
Content-Type: application/json

{
    "typeOp": "expenses",
    "amount": 40,
    "concept": "concept e"
}


### get operation
GET http://localhost:4000/api/op/allOp/0efc0fca-509f-401f-9f72-6518d2a02668


### update Operation
PUT http://localhost:4000/api/op/updateOp/6009c985-a357-4b65-ad47-5dc1610fc8a3
Content-Type: application/json

{
    "concept": "dev algo algo"
}

### delete Operation
DELETE http://localhost:4000/api/op/deleteOp/62728d51-bc97-4221-a01a-09d7f553a25a
Content-Type: application/json

{
    "concept": "dev algo algo"
}